sonata_admin:
    title: 'PDF Generator'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left,class: col-md-6 }
    options:
        legacy_twig_text_extension: false



sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
